version: '3'
services:

  # Контейнер для определения того, кто обрабатывает тот или иной запрос
  api.gatway:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"

  # Этот контейнер будет работать с авторизацией и аутентификацией пользователя
  api.auth:
    build: ./backend/auth
    volumes:
      - ./backend/auth/src:/usr/src/app
    command: sh -c "npm install && npm start"
    container_name: api.auth
    env_file:
      - .env

  api.azure.upload:
    build: backend/azure_storage
    volumes:
      - ./backend/azure_storage/src:/usr/src/app
    command: sh -c "npm install && npm start"
    container_name: api.azure.upload
    env_file:
      - .env

  # Контейнер для обмена сообщениями между микросервисами
  redis.sockets:
    image: 'redis:alpine'
    volumes:
      - './volumes/db/redis/sockets:/data'

  front.public:
    build: ./frontend/public
    volumes:
      - ./frontend/public:/usr/src/app
    command: sh -c "npm install && npm start"


  # Контейнер используется для агрегации сообщений по WebSocket протоколу
  rabbit.mq:
    image: rabbitmq:3.12.0-management-alpine
    env_file:
      - .env
    ports:
      - "5672:5672"
      - "15672:15672"
